Suave customization
blockscout/frontend pull request #1256
Opened 2023-10-05 13:34 UTC by tom2drum

Resolves #1243

2023-10-05 14:39 UTC, tom2drum commented on deploy/values/review/values.yaml.gotmpl
> +      _default: http
will rollback after PM review

2023-10-09 11:36 UTC, isstuev requested changes

2023-10-09 11:36 UTC, isstuev commented on pages/txs/computor/[hash].tsx
> +export { base as getServerSideProps } from 'nextjs/getServerSideProps';
I think there should be an env variable or some other way to return 404 error for chains that shouldn't have this page.

2023-10-09 17:28 UTC, isstuev approved these changes

2023-10-09 18:41 UTC, merged