Load categories from config and improve app sorting
blockscout/frontend pull request #1545
Opened 2024-01-26 16:49 UTC by maxaleks

Resolves https://github.com/blockscout/frontend/issues/1498

1. added a new ENV: `NEXT_PUBLIC_MARKETPLACE_CATEGORIES_URL`
2. made loading categories from a separate config file
3. improved app sorting

2024-01-29 13:07 UTC, tom2drum requested changes

2024-01-29 13:21 UTC, maxaleks commented on ui/marketplace/useMarketplaceCategories.tsx
> +    select: (data) => (data as Array<string>),
I don't think so. I was just following an example and decided not to delete anything that might be necessary

2024-01-29 13:24 UTC, maxaleks commented on ui/marketplace/useMarketplace.tsx
> +    let categoryNames: Array<string> = [];
> What if there is a fetch error? Or if the category config is not provided?

I think `categoriesData` would then be empty, wouldn't it?
https://github.com/blockscout/frontend/pull/1545/files#diff-2ebed5c8ee6bd0ee84fe6b654067cdee18307a229868afd84e6652d64a866517R85

2024-01-30 05:07 UTC, tom2drum commented
Can we make the tab skeleton resemble real tabs more? For instance, by adding additional tabs and increasing their width.

<img width="914" alt="image" src="https://github.com/blockscout/frontend/assets/22130104/36bfbccd-ade0-40b5-93cc-a5e9ec8e27cb">

2024-01-30 05:15 UTC, tom2drum commented on ui/marketplace/useMarketplace.tsx
> +    let categoryNames: Array<string> = [];
Oh yeah, you're right. I missed the condition for the placeholder data in the query hook.

2024-01-30 05:17 UTC, tom2drum approved these changes

2024-01-30 13:58 UTC, merged