Implemented an interpretation stub for failed transactions
blockscout/frontend pull request #2373
Opened 2024-11-07 23:03 UTC by IamLRBA

## In this adjusted code:

-  If an error occurs and showDegradedView is false, the code checks whether the error is custom. If not, it displays the message "**Address failed to call method on address**" in bold, red text.

- The error message is wrapped in a div alongside other content like the `TextAd` and `PageTitle`, ensuring the page structure is consistent.

2024-11-07 23:05 UTC, IamLRBA commented
cc
@NikitaSavik 
Please have a review at the PR and correct me where I may have gone wrong.
Thank you!

2024-11-27 01:09 UTC, IamLRBA commented
Hello @NikitaSavik, i have made this PR awaiting your approval.
Thanks!

2024-12-02 13:39 UTC, tom2drum commented
@IamLRBA Can you mark PR as "Ready for review" please?

2024-12-09 11:16 UTC, isstuev requested changes

2024-12-09 11:16 UTC, isstuev commented on ui/pages/Transaction.tsx
> +                Address failed to call method on address.
Hi! It's not exactly what the issue is about.
The idea was to implement a stub for transaction with a failed status, not an error state of the page.
Also, it has to be not the plain text, but addresses and method name from the transaction data.
And we use chakra-ui and variables for colors and paddings, so styling is not correct also

2025-01-11 15:56 UTC, isstuev commented
https://github.com/blockscout/frontend/pull/2484

2025-01-11 15:56 UTC, closed without merging